// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhAxgHBoeDq-SjiDAfhcT2T8Z-dAIgl5I',
    appId: '1:493520990271:web:288d5c9a24f8da881f088a',
    messagingSenderId: '493520990271',
    projectId: 'flutterchatapp-8caed',
    authDomain: 'flutterchatapp-8caed.firebaseapp.com',
    storageBucket: 'flutterchatapp-8caed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqMkiYVp3Naa14irYyeeA3Ibijdbf8nvM',
    appId: '1:493520990271:android:2ddd77faadbd6ae61f088a',
    messagingSenderId: '493520990271',
    projectId: 'flutterchatapp-8caed',
    storageBucket: 'flutterchatapp-8caed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaGt4a0U_gS32gH_ETDTdweaLUr0T0MuA',
    appId: '1:493520990271:ios:f1a6cdd2f937f5771f088a',
    messagingSenderId: '493520990271',
    projectId: 'flutterchatapp-8caed',
    storageBucket: 'flutterchatapp-8caed.firebasestorage.app',
    iosBundleId: 'com.example.chatAppKeren',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaGt4a0U_gS32gH_ETDTdweaLUr0T0MuA',
    appId: '1:493520990271:ios:f1a6cdd2f937f5771f088a',
    messagingSenderId: '493520990271',
    projectId: 'flutterchatapp-8caed',
    storageBucket: 'flutterchatapp-8caed.firebasestorage.app',
    iosBundleId: 'com.example.chatAppKeren',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhAxgHBoeDq-SjiDAfhcT2T8Z-dAIgl5I',
    appId: '1:493520990271:web:7edc84699b7cd4ea1f088a',
    messagingSenderId: '493520990271',
    projectId: 'flutterchatapp-8caed',
    authDomain: 'flutterchatapp-8caed.firebaseapp.com',
    storageBucket: 'flutterchatapp-8caed.firebasestorage.app',
  );

}